# FROM djja/angular:latest as build
FROM node:14.20 as build

# RUN npm update
RUN npm install -g @angular/cli

WORKDIR /app
COPY . .

RUN npm install
RUN ng build --configuration production


FROM nginx:alpine
COPY --from=build /app/dist/fit-flex/ /usr/share/nginx/html
COPY nginxconf /etc/nginx/conf.d/default.conf
