version: '3.7'

services:
  bff:
    build:
      context: BFF/BFF
    restart: on-failure
    ports:
      - 3000:80
    environment:
      # ASPNETCORE_URLS: http://+:5000
      DB_CONNECTION_STRING: 'Server=sqlserver;Database=BFF;User Id=sa;Password=Geheim_101'