apiVersion: apps/v1
kind: Deployment
metadata:
    name: klant-service
spec:
  replicas: 1
  selector:
    matchLabels:
        app: klant-service
  template:
    metadata:
      labels:
        app: klant-service
    spec:
      containers:
        - name: klant-service
          image: djja/fit-klantservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: DB_CONNECTION_STRING
              value: 'Server=mssql;Database=fit;User ID=sa;Password=Your(!)Strongpassword'
            - name: BROKER_CONNECTION_STRING
              value: amqp://guest:guest@localhost:5672
            - name: BROKER_EXCHANGE_NAME
              value: 'Fit.Messagebus'
