apiVersion: apps/v1
kind: Deployment
metadata:
    name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
        app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: identity-configmap
      containers:
        - name: identity
          image: djja/fitflex-identity
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/Data
          env:
            - name: DB_CONNECTION_STRING
              value: 'Server=mssql;Database=identity;User ID=sa;Password=Your(!)Strongpassword'
            - name: REGISTER_ENABLED
              value: 'true'
            - name: ASPNETCORE_URLS
              value: http://*:80/
            - name: CONFIG_PATH_CLIENTS
              value: /app/Data/clients.json
            - name: CONFIG_PATH_IDS
              value: /app/Data/ids.json
            - name: CONFIG_PATH_APIS
              value: /app/Data/apis.json
