version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Geheim_101
    ports:
      - 1433:1433
    volumes:
      - /d/data/fitdb2/fitdb/mssql-data:/var/opt/mssql/data