apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      # volumes:
      #   - name: mssql-pvc
      #     persistentVolumeClaim:
      #       claimName: mssql-pvc
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-18.04
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          volumeMounts:
            # - mountPath: /var/opt/mssql
            #   name: mssql-pvc
        #   resources:
        #     limits:
        #       cpu: 500m
        #       memory: 512Mi
        #     requests:
        #       cpu: 40m
        #       memory: 20Mi
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              # value: Your(!)Strongpassword
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: password