apiVersion: apps/v1
kind: Deployment
metadata:
    name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
        app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: identity-configmap
      containers:
        - name: identity
          image: djja/fit-identityservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/Data
          env:
            - name: REGISTER_ENABLED
              value: 'true'
            - name: ASPNETCORE_URLS
              value: http://*:80/
            - name: CONFIG_PATH_CLIENTS
              value: /app/Data/clients.json
            - name: CONFIG_PATH_IDS
              value: /app/Data/ids.json
            - name: CONFIG_PATH_APIS
              value: /app/Data/apis.json
            - name: PUBLIC_ORIGIN
              value: https://identity.dirk-jan.eu
            - name: REGISTER_REDIRECT_URL
              value: https://fit.dirk-jan.eu/fit
            - name: BROKER_EXCHANGE_NAME
              value: 'Fit.Messagebus'
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: identityservice-secret
                  key: dbConnectionString
            - name: BROKER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-connectionstring-secret
                  key: connectionString
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: identityservice-secret
                  key: adminUsername
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identityservice-secret
                  key: adminPassword
