// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestatieService.DAL;

namespace PrestatieService.Migrations
{
    [DbContext(typeof(PrestatieContext))]
    partial class PrestatieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrestatieService.Models.Prestatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Gewicht")
                        .HasColumnType("float");

                    b.Property<double>("Herhalingen")
                        .HasColumnType("float");

                    b.Property<Guid>("KlantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OefeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Opmerking")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prestaties");
                });
#pragma warning restore 612, 618
        }
    }
}
