FROM djja/angular:20200403 as build

WORKDIR /app
Copy . .

RUN npm install
RUN ng build --prod --configuration production


FROM nginx:alpine
COPY --from=build /app/dist/fit-flex/ /usr/share/nginx/html
COPY nginxconf /etc/nginx/conf.d/default.conf