apiVersion: v1
kind: Service
metadata:
  name: broker-nodeport
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: 5672
      name: service
      targetPort: 5672
      nodePort: 31672
    - port: 15672
      name: management
      targetPort: 15672
      nodePort: 31673