apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    service: broker
spec:
  selector:
    service: broker
  ports:
    - name: bus  
      port: 5672
    - name: management  
      port: 15672

