version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Geheim_101
    ports:
      - 1433:1433
  # mysql:
  #   image: mysql:8.0.19
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: spekkie
  #     MYSQL_USER: spekkie
  #     MYSQL_PASSWORD: spekkie
  #   ports:
  #     - 3306:3306