apiVersion: apps/v1
kind: Deployment
metadata:
    name: prestatie-service
spec:
  replicas: 1
  selector:
    matchLabels:
        app: prestatie-service
  template:
    metadata:
      labels:
        app: prestatie-service
    spec:
      containers:
        - name: prestatie-service
          image: djja/fit-prestatieservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: BROKER_EXCHANGE_NAME
              value: 'Fit.Messagebus'
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: prestatieservice-secret
                  key: dbConnectionString
            - name: BROKER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-connectionstring-secret
                  key: connectionString
