apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    certmanager.k8s.io/issuer: "letsencrypt-production"
spec:
  rules:
    - host: bff.fit.dirk-jan.eu
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: bff
              servicePort: 80
    - host: fit.dirk-jan.eu
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: fit-frontend
              servicePort: 80
    - host: identity.dirk-jan.eu
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: identity
              servicePort: 80