version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Geheim_101
  mysql:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spekkie
      MYSQL_USER: spekkie
      MYSQL_PASSWORD: spekkie
    ports:
      - 3306:3306
  bff:
    build:
      context: BFF/BFF
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      # ASPNETCORE_URLS: http://+:5000
      DB_CONNECTION_STRING: 'Server=sqlserver;Database=BFF;User Id=sa;Password=Geheim_101'