apiVersion: apps/v1
kind: Deployment
metadata:
    name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: djja/fit-bff
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: DB_CONNECTION_STRING
              value: 'Server=mssql;Database=fit;User ID=sa;Password=Your(!)Strongpassword'
            - name: AUTH_AUTHORITY
              value: 'https://identity.dirk-jan.eu'
            - name: BROKER_CONNECTION_STRING
              value: amqp://guest:guest@broker:5672
            - name: BROKER_EXCHANGE_NAME
              value: 'Fit.Messagebus'
