name: BFF

on:
  push:
    branches: [ master ]
    # paths: 
    # - src/BFF/**
  pull_request:
    branches: [ master ]
    paths: 
    - src/BFF/**


jobs:
  vars:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      DockerImange: djja/fit-bff
      ProjectPath: src/BFF/BFF
      ManifestsPath: common/deployment/manifests/BFF
    steps:
      - name: Setting vars
        run: echo setting vars...
      
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [vars]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0

    - name: Dotnet Publish
      run: dotnet publish ${{ needs.vars.outputs.ProjectPath }} -c Release -o ${{ needs.vars.outputs.ProjectPath }}/obj/docker/publish

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: djja
        password: ${{ secrets.DOCKERHUBTOKEN }}
        repository: ${{ needs.vars.outputs.DockerImange }}
        path: ${{ needs.vars.outputs.ProjectPath }}
        tags: ${{ github.sha }}
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true

  deploy:
    name: Deploy on Kubernetes cluster
    runs-on: ubuntu-latest
    needs: [vars, build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1
        with:
          namespace: fit
          manifests: |
            ${{ needs.vars.outputs.ManifestsPath }}/deployment.yaml
            ${{ needs.vars.outputs.ManifestsPath }}/service.yaml
          images: ${{ needs.vars.outputs.DockerImange }}:${{ github.sha }}
          
          
